[package]
name = "wgpu-renderer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.19.0"
winit = "0.29.15"
pollster = "0.3.0"
